import type { LabTest, Shoe, ShoesFile } from '../../../shared/types.js';
import { categoricalValue, PLATE_LABELS } from './categorical';
import { displayNumber, indexTests, numericValue, type TestIndex } from './dataset';
import { columnLabel } from './labels';
import { DERIVED_ZONE_PAIRS } from './lineage';
import { displayReleaseDate } from './release-date';
import { headerUnits } from './units';

/**
 * How wide the desktop table would have to be, in pixels, computed rather than measured — the whole
 * point being that it can be asked BEFORE the table is mounted, so `Page.svelte` picks the rendering
 * that fits instead of mounting one and watching it overflow
 * (docs/app.md §Two renderings, and only one of them mounted).
 *
 * Nothing here touches the DOM. A model that measured a mounted table could only ever answer for the
 * rendering already on screen, and switching on that answer is a feedback loop: mount the desktop
 * table, measure it too wide, mount the phone one, measure nothing, mount the desktop table again.
 *
 * The inputs are of three kinds and it is worth knowing which is which when one of them moves:
 *
 * 1. **Tokens** — the paddings, the name column, the caret. Read off `app.css` and `ShoeTable.svelte`
 *    and listed once, below.
 * 2. **Font tables** — generated by `app/scripts/measure-label-widths.mjs` and committed. Each is
 *    specific to a face, a size, a weight AND a tracking; the block above each one names all four.
 * 3. **The loaded fleet** — the widest string each phrase column actually renders, which no constant
 *    can state because it is upstream's. Computed once per dataset and memoised by `fitModel`.
 */

/* ─ tokens ─ The one home for the geometry this model is built out of. Every number is a CSS
   declaration this file cannot see, so each names where it is written. */
/** `td.name { min-width: 14rem }` in `ShoeTable.svelte`, against the 16px root. Content box: the
 *  repo is `content-box` throughout bar `.scrollport`, so the padding below is on top of it. */
const NAME_COL_PX = 224;
/** `--s2` either side, the `th`/`td` padding. */
const CELL_PAD_PX = 16;
/** `--caret-w`. Drawn in every sortable header, sorted or not, so it is in every column's minimum —
 *  once, on the name line, whichever end of the name it takes. */
const CARET_PX = 12;
/** `.tblwrap`'s two 1px side borders. The model answers for the panel, because the panel is what has
 *  to fit the content track. */
const WRAPPER_BORDER_PX = 2;
/**
 * `.content { padding: 0 var(--s4) }` in `Page.svelte`, the LEADING gutter only — deliberately, and
 * this is the one number in here that is a judgement rather than a transcription.
 *
 * The question this model answers is: would the document scroll sideways. A block's trailing padding is not part of its scrollable overflow in any engine, so a
 * table that overruns its content box by up to 16px still leaves `scrollWidth` equal to the window —
 * measured on the real fleet, where the default view's document is 917px against a 902px panel and a
 * pair of 16px gutters. Counting both gutters would make the model reject widths at which nothing
 * scrolls; counting neither would let the table run to the window's edge. `FIT_SLACK_PX` below is
 * what keeps the trailing gutter's air: it is the margin the table must clear the window by, so at
 * the width the model first says yes the gutter is there.
 */
const CONTENT_GUTTER_PX = 16;
/** `--sidebar-w`, the permanent sidebar's grid track. */
const SIDEBAR_TRACK_PX = 260;

/**
 * The FLOOR under the width at which the sidebar stops being a drawer and takes a column of its own
 * (docs/app.md §Filters). A floor and not the boundary itself: `sidebarPermanentAt` below is the
 * boundary, and for any column set wider than the default it stands further out.
 *
 * **It is a LAYOUT width**, like every other number in this file — `documentElement.clientWidth`,
 * which a classic scrollbar has already been subtracted from. Written as a media query it would be
 * a WINDOW width instead, and the two differ by exactly the scrollbar: the sidebar would claim its
 * column 12–15px of window before the fit decision could know it had, and mount a table up to 173px
 * too wide in the gap. A browser drawing classic scrollbars therefore stands the sidebar up at a
 * ~1203–1206px window, which is this number seen from outside the layout rather than a different
 * one.
 *
 * It is derived from the rule below rather than measured against it: it is the first width at which
 * the **default view** still fits beside the track, which is
 * `desktopMinWidth(defaults) + FIT_SLACK_PX + CONTENT_GUTTER_PX + SIDEBAR_TRACK_PX` — 903 + 12 + 16
 * + 260 on today's fleet. Chosen against any other criterion it opens a band where the rendering
 * reads desktop → list → desktop as a window is dragged WIDER, because taking the track costs the
 * table 260px at one pixel of window: 1180 is where the page merely fits, with 2px in hand against
 * the 12 the fit rule holds it to, and 1180–1190px is the band that buys.
 * `hunt/fit-boundary.mjs` is where the derivation is checked, because only the real fleet can state
 * the 903.
 */
export const SIDEBAR_PERMANENT_PX = 1191;

/**
 * Below this the phone rendering, whatever the arithmetic says. A two-column desktop table is not a
 * design on a phone — it spends 40% of the width on the name and shows two numbers — so the fit
 * question is only asked above the floor (docs/app.md §Two renderings, and only one of them mounted).
 */
export const DESKTOP_FLOOR_PX = 700;

/**
 * The margin the desktop rendering must clear the available width by. It absorbs the model's own
 * error — the font tables are per-character advances and the browser's line breaking is not obliged
 * to agree with a sum to the pixel — and it is what keeps the decision one-sided: the cost of being
 * a few pixels pessimistic is a phone rendering at a width the table would just have squeezed into,
 * and the cost of being a pixel optimistic is a document that scrolls sideways, which is the defect
 * this model exists to remove.
 */
export const FIT_SLACK_PX = 12;

/**
 * Per-character advances for **Inter Tight 600 at 14.72px (`--t-md`) with no tracking** — the
 * desktop header face (`ShoeTable.svelte`, `th button`). Generated by
 * `app/scripts/measure-label-widths.mjs`; regenerate it if the face, the size, the weight or the
 * tracking moves, because every number is specific to all four.
 *
 * **Chromium's**, like `labels.ts`'s, and not a per-character maximum over the three engines. The
 * maximum was tried and measured worse: the engines disagree by at most 0.51px on a character and by
 * ~2px on a whole column set, but summing per-character maxima sums disagreements that never co-occur
 * in one engine, which put the model 8–15px over what every engine rendered. `FIT_SLACK_PX` covers
 * the spread instead — it is 5× the widest column set's — and `cross-browser.spec.ts` measures the
 * model against all three engines so it cannot drift there unseen.
 */
const HEADER_PX: Record<string, number> = {
  '0': 9, '1': 6, '2': 9, '3': 9, '4': 9, '5': 9, '6': 9, '7': 8, '8': 9, '9': 9,
  a: 8, b: 9, c: 8, d: 9, e: 8, f: 5, g: 9, h: 9, i: 3, j: 3, k: 8, l: 3, m: 13, n: 8, o: 8,
  p: 9, q: 9, r: 5, s: 8, t: 5, u: 8, v: 8, w: 12, x: 8, y: 8, z: 8,
  A: 10, B: 9, C: 10, D: 10, E: 8, F: 8, G: 11, H: 10, I: 4, J: 8, K: 9, L: 8, M: 13, N: 10,
  O: 11, P: 9, Q: 11, R: 9, S: 9, T: 9, U: 10, V: 10, W: 14, X: 10, Y: 10, Z: 9,
  ' ': 3, '.': 4, ',': 4, ':': 4, ';': 4, '/': 5, '(': 5, ')': 5, '%': 12, '+': 9, '-': 6,
  '£': 9, '—': 15, 'Δ': 9.88,
};

/**
 * The same table for **Inter Tight 400 at 14.72px with no tracking** — the phrase cells
 * (`td.num:not(.fig)`: plate, release date and every categorical column). A separate table rather
 * than the header's scaled, because Inter Tight is a variable face and 400 is not 600 narrowed.
 */
const PHRASE_PX: Record<string, number> = {
  '0': 9, '1': 5, '2': 8, '3': 9, '4': 9, '5': 8, '6': 8, '7': 8, '8': 8, '9': 8,
  a: 8, b: 8, c: 8, d: 8, e: 8, f: 5, g: 8, h: 8, i: 3, j: 3, k: 7, l: 3, m: 12, n: 8, o: 8,
  p: 8, q: 8, r: 5, s: 7, t: 5, u: 8, v: 8, w: 11, x: 7, y: 8, z: 7,
  A: 9, B: 9, C: 10, D: 10, E: 8, F: 8, G: 10, H: 10, I: 3, J: 7, K: 9, L: 8, M: 12, N: 10,
  O: 11, P: 9, Q: 11, R: 9, S: 9, T: 9, U: 10, V: 9, W: 13, X: 9, Y: 9, Z: 9,
  ' ': 3, '.': 4, ',': 4, ':': 4, ';': 4, '/': 5, '(': 5, ')': 5, '%': 11, '+': 9, '-': 6,
  '£': 9, '—': 15, 'Δ': 9.41,
};

/** Wider than anything either table holds, so an unmeasured character can only ever make the model
 *  pessimistic. Both tables report the same figure, which is why there is one constant. */
const FALLBACK_PX = 15;

/**
 * One number, because the figure face is monospaced: **JetBrains Mono 400 at 14.72px with -0.02em**
 * (`td.fig`), where every character measured — digits, the em dash, the separators — takes the same
 * advance. `tabular-nums` is what makes that exact rather than approximate.
 */
const FIGURE_ADVANCE_PX = 8.71;

/** The same for the units line, **JetBrains Mono 400 at 12px (`--t-xs`), no tracking**. */
const UNITS_ADVANCE_PX = 7;

/**
 * The widest a resolved story score can render. Scores are the one column whose values depend on the
 * view rather than on the shoe (docs/app.md §The story scores), so they are not in the dataset the
 * model is built from — and a stated bound is the honest answer: `displayNumber` gives at most two
 * decimals, so six characters covers `100` and `-12.34` alike, and a score column's header is wider
 * than its figures anyway at every label the registry produces.
 */
const SCORE_CELL_CHARS = 6;

const textPx = (s: string, table: Record<string, number>): number =>
  [...s].reduce((sum, ch) => sum + (table[ch] ?? FALLBACK_PX), 0);

/**
 * What a wrapping box cannot go under: its longest word. The desktop headers wrap deliberately —
 * `nowrap` on a `th` made every column's minimum its longest header — so this, not the whole
 * label, is a header's contribution (docs/app.md §Columns and sorting).
 *
 * A hyphen is a break opportunity and the break comes AFTER it, so `stack-height-heel` is three
 * words and the widest of them carries the hyphen. That matters for exactly the columns a URL is
 * allowed to name and the catalogue no longer holds: their header is the raw slug
 * (docs/app.md §Columns are permissive, ranges and sorts are strict), and treating one as a single
 * unbreakable word measured 150px against a rendered 76px in both engines.
 */
const widestWordPx = (s: string, table: Record<string, number>): number =>
  Math.max(0, ...s.split(/\s+/).flatMap((w) => w.split(/(?<=-)/)).map((w) => textPx(w, table)));

/**
 * A header's min-content: the name line and the units line, whichever is wider. The caret sits on
 * the NAME line in every column — trailing it in a phrase column, LEADING it in a figure one, so
 * the label can keep the edge its figures keep — so it is counted once, there, and the units line
 * reserves nothing beside it (docs/app.md §Table presentation).
 *
 * ADDITIVE, and that is a fact about the box rather than about the text: the mark and the name are
 * flex items of `.h-line`, and flex items cannot break apart, so the line's minimum is the longest
 * word plus the whole mark. It would not be additive if the mark sat in the text's own flow — the
 * engines break either side of an atomic inline — but that layout was tried and rejected for
 * putting the mark on a line of its own (`ShoeTable.svelte`, `.h-line`).
 */
export function headerMinPx(key: string, test: LabTest | undefined): number {
  // The units line is mono and cannot wrap — no unit string carries a space now that `size-rating`
  // reads `3=TTS`, and `MAX_UNITS_CLEAR_PX` in `labels.ts` is what keeps it that short — so its width is
  // a character count over the whole line (docs/app.md §Table presentation).
  const unitsPx = headerUnits(key, test).length * UNITS_ADVANCE_PX;
  return Math.max(widestWordPx(columnLabel(key, test), HEADER_PX) + CARET_PX, unitsPx);
}

/**
 * The widest cell in a column. A figure is one mono token, so its width is its length; a phrase
 * carries `white-space: nowrap` and cannot wrap at all, so the whole string is its minimum — which
 * is why the release date column, printing `September 2024`, is one of the widest in the default
 * set (docs/app.md §Table presentation).
 */
export function cellMaxPx(key: string, shoes: readonly Shoe[], idx: TestIndex,
  scoreKeys: ReadonlySet<string>): number {
  if (scoreKeys.has(key)) return SCORE_CELL_CHARS * FIGURE_ADVANCE_PX;
  let widest = 0;
  for (const shoe of shoes) {
    let px: number;
    if (key === 'releasedAt') {
      px = textPx(displayReleaseDate(shoe.releasedAt, shoe.releaseDateSource), PHRASE_PX);
    } else if (key === 'plate') {
      px = textPx(PLATE_LABELS[shoe.plate], PHRASE_PX);
    } else {
      const cat = categoricalValue(shoe, key, idx);
      if (cat !== undefined) px = textPx(cat, PHRASE_PX);
      else {
        const v = key === 'score' ? shoe.score : numericValue(shoe, key, idx);
        px = (v === null || v === undefined ? 1 : displayNumber(v).length) * FIGURE_ADVANCE_PX;
      }
    }
    if (px > widest) widest = px;
  }
  return widest;
}

/**
 * What the model is: one memoised width per column, over the fleet that is actually loaded. Built
 * once per dataset, because the widest phrase in a column is a fact about the data and nothing a
 * runner does can change it — while the set of columns on screen changes with every tick of the
 * picker, which is why the width is per column and the sum is per call.
 */
export interface FitModel {
  /** The column's min-content width including its cell padding. */
  columnPx(key: string): number;
}

/**
 * The score columns, from the pair registry rather than from the scoring engine: a further story
 * arrives here with no edit, and this file needs to know only that these are the columns whose
 * values come from the view rather than from the dataset (docs/app.md §The story scores).
 */
const SCORE_COLUMN_KEYS: ReadonlySet<string> = new Set(
  DERIVED_ZONE_PAIRS.flatMap((p) => [p.heel, p.forefoot]));

export function fitModel(data: ShoesFile, index?: TestIndex): FitModel {
  const idx = index ?? indexTests(data.tests);
  const cache = new Map<string, number>();
  return {
    columnPx(key: string): number {
      const hit = cache.get(key);
      if (hit !== undefined) return hit;
      const test = idx.bySlug.get(key);
      const px = CELL_PAD_PX + Math.max(headerMinPx(key, test),
        cellMaxPx(key, data.shoes, idx, SCORE_COLUMN_KEYS));
      cache.set(key, px);
      return px;
    },
  };
}

/**
 * The desktop table's min-content width, panel borders included — what has to fit the content track.
 * The name column is a floor rather than a measurement: `min-width: 14rem` is wider than the widest
 * word any shoe name carries, which `hunt/fit-boundary.mjs` checks against the real fleet.
 */
export function desktopMinWidth(columns: readonly string[], model: FitModel): number {
  return NAME_COL_PX + CELL_PAD_PX + WRAPPER_BORDER_PX
    + columns.reduce((sum, col) => sum + model.columnPx(col), 0);
}

/**
 * The first layout width at which the sidebar takes a column of its own beside **these** columns:
 * the floor, or the width at which the table still clears the track by the fit rule's own slack,
 * whichever is further out (docs/app.md §Filters).
 *
 * The `max` is the whole rule, and it is what makes the two decisions one. The track costs the table
 * 260px at a single pixel of window, so a permanence boundary that cannot see the column set stands
 * the sidebar up at a width where the fit rule then refuses the table — and the rendering reads
 * desktop → list → desktop as the window is dragged WIDER. Moving the constant closes that for one
 * column set and leaves it open for every wider one — a nine-column view handed 170px of width back
 * to the stacked list at exactly 1191px — because a constant cannot answer a question about a set
 * the runner picks. Consulting the model closes it for every set at once, and gives the stronger
 * property the sidebar was always supposed to have: **it never stands beside the stacked list**,
 * because it waits for the table it exists to tune.
 */
export function sidebarPermanentAt(columns: readonly string[], model: FitModel): number {
  return Math.max(SIDEBAR_PERMANENT_PX,
    desktopMinWidth(columns, model) + FIT_SLACK_PX + CONTENT_GUTTER_PX + SIDEBAR_TRACK_PX);
}

/** Whether the sidebar is a column rather than a drawer at this layout width — the predicate
 *  `Page.svelte` drives the layout, the drawer's focus trap and the `Filters` trigger from, so all
 *  of them answer one boundary (docs/app.md §Filters). */
export function sidebarPermanent(columns: readonly string[], layoutWidth: number,
  model: FitModel): boolean {
  return layoutWidth >= sidebarPermanentAt(columns, model);
}

/** What the table has to lay itself out in: the width less the page's own gutter, less the
 *  sidebar's track wherever the sidebar has one (docs/app.md §Filters). */
export function availableForTable(columns: readonly string[], layoutWidth: number,
  model: FitModel): number {
  return layoutWidth - CONTENT_GUTTER_PX
    - (sidebarPermanent(columns, layoutWidth, model) ? SIDEBAR_TRACK_PX : 0);
}

/** The question in one line: would the desktop table fit, with the slack it is held to? */
export function fitsDesktop(columns: readonly string[], availableWidth: number,
  model: FitModel): boolean {
  return desktopMinWidth(columns, model) + FIT_SLACK_PX <= availableWidth;
}

/**
 * The mount decision itself, so the floor and the fit rule have one home and `Page.svelte` reads a
 * single predicate. `layoutWidth` is the LAYOUT width — `documentElement.clientWidth`, which excludes
 * a classic scrollbar — because that is the width the table is laid out in and the fleet is always
 * long enough to draw one.
 *
 * Monotone in the width by construction, which is the property that matters most here: below
 * `sidebarPermanentAt` the available width is `layoutWidth - 16` and rises with the window, above it
 * `layoutWidth - 276`, and the boundary is *defined* as a width at which the second still clears the
 * table's minimum. So the step down at the boundary can never cross the requirement, and a rendering
 * once mounted survives every wider window
 * (docs/app.md §Two renderings, and only one of them mounted).
 */
export function rendersPhone(columns: readonly string[], layoutWidth: number,
  model: FitModel): boolean {
  if (layoutWidth < DESKTOP_FLOOR_PX) return true;
  return !fitsDesktop(columns, availableForTable(columns, layoutWidth, model), model);
}
