import type { LabTest, Shoe, ShoesFile } from '../../../shared/types.js';
import { categoricalValue, PLATE_LABELS } from './categorical';
import { displayNumber, indexTests, numericValue, type TestIndex } from './dataset';
import { columnLabel, wordsOf } from './labels';
import { DERIVED_ZONE_PAIRS } from './lineage';
import { displayReleaseDate } from './release-date';
import { headerUnits } from './units';

/**
 * How wide the desktop table's columns are, in pixels, computed rather than measured — the whole
 * point being that they can be asked BEFORE the table is mounted, so `Page.svelte` picks the
 * rendering that fits instead of mounting one and watching it overflow
 * (docs/app.md §Two renderings, and only one of them mounted).
 *
 * Two widths per column, and they answer different questions. The **min-content** half is what the
 * table has to have, and it decides which rendering mounts. The **max-content** half is what a
 * column would take if nothing in it had to wrap; it decides nothing on its own, and exists for a
 * rule that shares a declared track between columns.
 *
 * Nothing here touches the DOM. A model that measured a mounted table could only ever answer for the
 * rendering already on screen, and switching on that answer is a feedback loop: mount the desktop
 * table, measure it too wide, mount the phone one, measure nothing, mount the desktop table again.
 *
 * The inputs are of three kinds and it is worth knowing which is which when one of them moves:
 *
 * 1. **Tokens** — the paddings, the name column, the caret. Read off `app.css` and `ShoeTable.svelte`
 *    and listed once, below. The name column's floor is the one exception and says so where it is
 *    written: a declared width leaves no cell floor for it to transcribe.
 * 2. **Font tables** — generated by `app/scripts/measure-label-widths.mjs` and committed. Each is
 *    specific to a face, a size, a weight AND a tracking; the block above each one names all four.
 * 3. **The loaded fleet** — the widest string each phrase column actually renders, which no constant
 *    can state because it is upstream's. Computed once per dataset and memoised by `fitModel`.
 */

/* ─ tokens ─ The one home for the geometry this model is built out of. Every number is a CSS
   declaration this file cannot see, so each names where it is written. */
/**
 * The name column's floor, `14rem` against the 16px root, and the padding below is on top of it.
 *
 * **A declaration of this model's own, and no longer a transcription.** It was
 * `td.name { min-width: 14rem }` in `ShoeTable.svelte` until that table's widths became declared:
 * a `<col>` under `table-layout: fixed` beats every `min-width` on the cells in its column —
 * measured in all three engines, a column asking 60px renders 60px — so the CSS floor was inert and
 * was removed rather than left reading as a guarantee. It reaches the column through `columnPx`
 * below, which is the only route left (docs/app.md §Table presentation).
 *
 * **Exported because two things outside this file need the floor and neither can read a CSS rule
 * that no longer exists**: the loading placeholder reserves a `14rem` name track (`App.svelte`),
 * and `e2e/fit-support.ts` has to hand an engine this floor before asking it for a min-content the
 * model can be compared with.
 *
 * **Where it is still pinned, now that the CSS home is gone.** `smoke.spec.ts` holds the
 * placeholder's own `14rem` track to this number, which is what stops the two declarations of one
 * design fact drifting apart; and `fit.test.ts` pins `columnPx('name')` at `224 + 16` against the
 * committed fleet. The min-content comparison in `fit-support.ts` is NOT one of them — it consumes
 * this constant on both sides, so the floor is an identity term there and cannot be seen to move.
 */
export const NAME_COL_PX = 224;
/** `--s2` either side, the `th`/`td` padding. */
const CELL_PAD_PX = 16;
/** `--caret-w`. Drawn in every sortable header, sorted or not, so it is in every column's minimum —
 *  once, on the name line, whichever end of the name it takes. */
const CARET_PX = 12;
/** `.tblwrap`'s two 1px side borders. The model answers for the panel, because the panel is what has
 *  to fit the content track. */
const WRAPPER_BORDER_PX = 2;
/**
 * `.content { padding: 0 var(--s4) }` in `Page.svelte`, the LEADING gutter only — deliberately, and
 * this is the one number in here that is a judgement rather than a transcription.
 *
 * The question this model answers is: would the document scroll sideways. A block's trailing padding is not part of its scrollable overflow in any engine, so a
 * table that overruns its content box by up to 16px still leaves `scrollWidth` equal to the window —
 * measured on the real fleet, where the default view's document is 917px against a 902px panel and a
 * pair of 16px gutters. Counting both gutters would make the model reject widths at which nothing
 * scrolls; counting neither would let the table run to the window's edge. `FIT_SLACK_PX` below is
 * what keeps the trailing gutter's air: it is the margin the table must clear the window by, so at
 * the width the model first says yes the gutter is there.
 */
const CONTENT_GUTTER_PX = 16;
/** `--sidebar-w`, the permanent sidebar's grid track. */
const SIDEBAR_TRACK_PX = 260;
/** `.name-row { gap: var(--s2) }` in `ShoeTable.svelte` — between the chevron and the name. */
const NAME_ROW_GAP_PX = 8;
/**
 * The chevron's own advance. `.chev` is `›` in the body face at `--t-md`, so it is a single
 * character rather than an alphabet, and one measured number says more than a table entry would.
 * Generated by `app/scripts/measure-label-widths.mjs`, like the chip below it.
 */
const CHEV_PX = 5;
/**
 * The whole discontinued chip, its left margin included: `--s2` of margin, a 1px border and `--s1`
 * of padding each side, around `discontinued` set in the body face at `--t-xs` with 0.06em of
 * tracking and uppercased (`DiscontinuedTag.svelte`). ONE number rather than a fourth font table,
 * because the chip renders exactly one string — and the generator reads that string and its rule
 * out of the component, so neither can drift from this without the number moving.
 */
const DISC_TAG_PX = 110.64;

/**
 * The FLOOR under the width at which the sidebar stops being a drawer and takes a column of its own
 * (docs/app.md §Filters). A floor and not the boundary itself: `sidebarPermanentAt` below is the
 * boundary, and for any column set wider than the default it stands further out.
 *
 * **It is a LAYOUT width**, like every other number in this file — `documentElement.clientWidth`,
 * which a classic scrollbar has already been subtracted from. Written as a media query it would be
 * a WINDOW width instead, and the two differ by exactly the scrollbar: the sidebar would claim its
 * column 12–15px of window before the fit decision could know it had, and mount a table up to 173px
 * too wide in the gap. A browser drawing classic scrollbars therefore stands the sidebar up at a
 * ~1203–1206px window, which is this number seen from outside the layout rather than a different
 * one.
 *
 * It is derived from the rule below rather than measured against it: it is the first width at which
 * the **default view** still fits beside the track, which is
 * `desktopMinWidth(defaults) + FIT_SLACK_PX + CONTENT_GUTTER_PX + SIDEBAR_TRACK_PX` — 903 + 12 + 16
 * + 260 on today's fleet. Chosen against any other criterion it opens a band where the rendering
 * reads desktop → list → desktop as a window is dragged WIDER, because taking the track costs the
 * table 260px at one pixel of window: 1180 is where the page merely fits, with 2px in hand against
 * the 12 the fit rule holds it to, and 1180–1190px is the band that buys.
 * `hunt/fit-boundary.mjs` is where the derivation is checked, because only the real fleet can state
 * the 903.
 */
export const SIDEBAR_PERMANENT_PX = 1191;

/**
 * Below this the phone rendering, whatever the arithmetic says. A two-column desktop table is not a
 * design on a phone — it spends 40% of the width on the name and shows two numbers — so the fit
 * question is only asked above the floor (docs/app.md §Two renderings, and only one of them mounted).
 */
export const DESKTOP_FLOOR_PX = 700;

/**
 * The margin the desktop rendering must clear the available width by. It absorbs the model's own
 * error — the font tables are per-character advances and the browser's line breaking is not obliged
 * to agree with a sum to the pixel — and it is what keeps the decision one-sided: the cost of being
 * a few pixels pessimistic is a phone rendering at a width the table would just have squeezed into,
 * and the cost of being a pixel optimistic is a document that scrolls sideways, which is the defect
 * this model exists to remove.
 */
export const FIT_SLACK_PX = 12;

/**
 * Per-character advances for **Inter Tight 600 at 14.72px (`--t-md`) with no tracking** — the
 * desktop header face (`ShoeTable.svelte`, `th button`). Generated by
 * `app/scripts/measure-label-widths.mjs`; regenerate it if the face, the size, the weight or the
 * tracking moves, because every number is specific to all four.
 *
 * **Chromium's**, like `labels.ts`'s, and not a per-character maximum over the three engines. The
 * maximum was tried and measured worse: the engines disagree by at most 0.51px on a character and by
 * ~2px on a whole column set, but summing per-character maxima sums disagreements that never co-occur
 * in one engine, which put the model 8–15px over what every engine rendered. `FIT_SLACK_PX` covers
 * the spread instead — it is 5× the widest column set's — and `cross-browser.spec.ts` measures the
 * model against all three engines so it cannot drift there unseen.
 */
const HEADER_PX: Record<string, number> = {
  '0': 9, '1': 6, '2': 9, '3': 9, '4': 9, '5': 9, '6': 9, '7': 8, '8': 9, '9': 9,
  a: 8, b: 9, c: 8, d: 9, e: 8, f: 5, g: 9, h: 9, i: 3, j: 3, k: 8, l: 3, m: 13, n: 8, o: 8,
  p: 9, q: 9, r: 5, s: 8, t: 5, u: 8, v: 8, w: 12, x: 8, y: 8, z: 8,
  A: 10, B: 9, C: 10, D: 10, E: 8, F: 8, G: 11, H: 10, I: 4, J: 8, K: 9, L: 8, M: 13, N: 10,
  O: 11, P: 9, Q: 11, R: 9, S: 9, T: 9, U: 10, V: 10, W: 14, X: 10, Y: 10, Z: 9,
  ' ': 3, '.': 4, ',': 4, ':': 4, ';': 4, '/': 5, '(': 5, ')': 5, '%': 12, '+': 9, '-': 6,
  '£': 9, '—': 15, 'Δ': 9.88,
};

/**
 * The same table for **Inter Tight 400 at 14.72px with no tracking** — the phrase cells
 * (`td.num:not(.fig)`: plate, release date and every categorical column). A separate table rather
 * than the header's scaled, because Inter Tight is a variable face and 400 is not 600 narrowed.
 */
const PHRASE_PX: Record<string, number> = {
  '0': 9, '1': 5, '2': 8, '3': 9, '4': 9, '5': 8, '6': 8, '7': 8, '8': 8, '9': 8,
  a: 8, b: 8, c: 8, d: 8, e: 8, f: 5, g: 8, h: 8, i: 3, j: 3, k: 7, l: 3, m: 12, n: 8, o: 8,
  p: 8, q: 8, r: 5, s: 7, t: 5, u: 8, v: 8, w: 11, x: 7, y: 8, z: 7,
  A: 9, B: 9, C: 10, D: 10, E: 8, F: 8, G: 10, H: 10, I: 3, J: 7, K: 9, L: 8, M: 12, N: 10,
  O: 11, P: 9, Q: 11, R: 9, S: 9, T: 9, U: 10, V: 9, W: 13, X: 9, Y: 9, Z: 9,
  ' ': 3, '.': 4, ',': 4, ':': 4, ';': 4, '/': 5, '(': 5, ')': 5, '%': 11, '+': 9, '-': 6,
  '£': 9, '—': 15, 'Δ': 9.41,
};

/**
 * The same table again for **Inter Tight 700 at 14.72px with no tracking** — the shoe name, which is
 * a `<strong>` and therefore takes the UA's `bolder` against a 400 parent. A third table rather than
 * either neighbour scaled, for the reason `PHRASE_PX` gives: the face is variable, and 700 is not
 * 600 widened any more than 600 is 400 widened.
 *
 * **This is the one table whose engine spread is worth a warning, and the warning is about NAMES
 * rather than about the column they feed.** Chromium reports whole-pixel advances at this size where
 * Firefox and WebKit report fractional ones, and a shoe name runs to 40 characters where a header
 * label is half that. Measured per name over all 455 the real fleet carries: Chromium is within 2px
 * of every one of them, while Firefox and WebKit reach **8.73px** and exceed `FIT_TOLERANCE_PX` on
 * 96 and 93 names respectively. Nor is it one-sided — the model comes out NARROWER than the engine
 * on two names, by up to 0.63px. That is the same trade `FIT_SLACK_PX` already absorbs (one engine's
 * table plus slack, rather than a per-character maximum that sums disagreements never seen together
 * — `app/scripts/measure-label-widths.mjs` owns the reasoning), seen on strings twice as long.
 *
 * **`columnMaxPx` is insulated from all of that, and a second consumer will not be.** It takes the
 * widest name in the fleet and hands it to a rule that shares a track, so the error can only move
 * where slack lands — it floors nothing, and nothing clips from it. Anything that reads a SINGLE
 * name's width, a greedy line-break simulation above all, inherits the figures above in both
 * directions and has to state its own tolerance rather than borrow this paragraph's conclusion.
 */
const NAME_PX: Record<string, number> = {
  '0': 10, '1': 6, '2': 9, '3': 9, '4': 10, '5': 9, '6': 9, '7': 8, '8': 9, '9': 9,
  a: 8, b: 9, c: 8, d: 9, e: 8, f: 5, g: 9, h: 9, i: 4, j: 4, k: 8, l: 4, m: 13, n: 9, o: 9,
  p: 9, q: 9, r: 6, s: 8, t: 5, u: 9, v: 8, w: 12, x: 8, y: 8, z: 8,
  A: 11, B: 9, C: 11, D: 10, E: 9, F: 8, G: 11, H: 11, I: 4, J: 8, K: 10, L: 8, M: 13, N: 10,
  O: 11, P: 9, Q: 11, R: 9, S: 9, T: 9, U: 10, V: 11, W: 15, X: 10, Y: 10, Z: 9,
  ' ': 3, '.': 4, ',': 5, ':': 4, ';': 5, '/': 5, '(': 5, ')': 5, '%': 12, '+': 10, '-': 6,
  '£': 9, '—': 15, 'Δ': 9.88,
};

/** Wider than anything any of the tables holds, so an unmeasured character can only ever make the
 *  model pessimistic. All three report the same figure, which is why there is one constant. */
const FALLBACK_PX = 15;

/**
 * One number, because the figure face is monospaced: **JetBrains Mono 400 at 14.72px with -0.02em**
 * (`td.fig`), where every character measured — digits, the em dash, the separators — takes the same
 * advance. `tabular-nums` is what makes that exact rather than approximate.
 */
const FIGURE_ADVANCE_PX = 8.71;

/** The same for the units line, **JetBrains Mono 400 at 12px (`--t-xs`), no tracking**. */
const UNITS_ADVANCE_PX = 7;

/**
 * The widest a resolved story score can render. Scores are the one column whose values depend on the
 * view rather than on the shoe (docs/app.md §The story scores), so they are not in the dataset the
 * model is built from — and a stated bound is the honest answer: `displayNumber` gives at most two
 * decimals, so six characters covers `100` and `-12.34` alike, and a score column's header is wider
 * than its figures anyway at every label the registry produces.
 */
const SCORE_CELL_CHARS = 6;

const textPx = (s: string, table: Record<string, number>): number =>
  [...s].reduce((sum, ch) => sum + (table[ch] ?? FALLBACK_PX), 0);

/**
 * What a wrapping box cannot go under: its longest word. The desktop headers wrap deliberately —
 * `nowrap` on a `th` made every column's minimum its longest header — so this, not the whole
 * label, is a header's contribution (docs/app.md §Columns and sorting).
 *
 * A word is `wordsOf`'s: split at the three separators every engine breaks at and drops, hyphens
 * kept. That rule has one home in `labels.ts` and it is deliberate over-reservation rather than a
 * model of anyone's line breaking — the price is a raw slug header wider than the engine would have
 * drawn it, and the alternative is a header hanging out of a declared column in whichever engine
 * the rule was not tuned to.
 */
const widestWordPx = (s: string, table: Record<string, number>): number =>
  Math.max(0, ...wordsOf(s).map((w) => textPx(w, table)));

/**
 * A header's min-content: the name line and the units line, whichever is wider. The caret sits on
 * the NAME line in every column — trailing it in a phrase column, LEADING it in a figure one, so
 * the label can keep the edge its figures keep — so it is counted once, there, and the units line
 * reserves nothing beside it (docs/app.md §Table presentation).
 *
 * ADDITIVE, and that is a fact about the box rather than about the text: the mark and the name are
 * flex items of `.h-line`, and flex items cannot break apart, so the line's minimum is the longest
 * word plus the whole mark. It would not be additive if the mark sat in the text's own flow — the
 * engines break either side of an atomic inline — but that layout was tried and rejected for
 * putting the mark on a line of its own (`ShoeTable.svelte`, `.h-line`).
 */
export function headerMinPx(key: string, test: LabTest | undefined): number {
  // The units line is mono and cannot wrap — no unit string carries a space now that `size-rating`
  // reads `3=TTS`, and `MAX_UNITS_CLEAR_PX` in `labels.ts` is what keeps it that short — so its width is
  // a character count over the whole line (docs/app.md §Table presentation).
  const unitsPx = headerUnits(key, test).length * UNITS_ADVANCE_PX;
  return Math.max(widestWordPx(columnLabel(key, test), HEADER_PX) + CARET_PX, unitsPx);
}

/**
 * A header's max-content: the same two lines, with the name line unwrapped. The sibling of
 * `headerMinPx`, and deliberately built the same way — `textPx` where that takes `widestWordPx`,
 * and the caret and the units line exactly as it reserves them, so the two can only ever differ by
 * how much of the label fits on one line.
 *
 * The units line is the SAME term in both, not a second measurement: it is mono, it carries no
 * space, and `MAX_UNITS_CLEAR_PX` in `labels.ts` is what keeps it short enough never to wrap — so
 * it has one width and this is it (docs/app.md §Table presentation).
 */
export function headerMaxPx(key: string, test: LabTest | undefined): number {
  const unitsPx = headerUnits(key, test).length * UNITS_ADVANCE_PX;
  return Math.max(textPx(columnLabel(key, test), HEADER_PX) + CARET_PX, unitsPx);
}

/**
 * The widest cell in a column. A figure is one mono token, so its width is its length; a phrase
 * carries `white-space: nowrap` and cannot wrap at all, so the whole string is its minimum — which
 * is why the release date column, printing `September 2024`, is one of the widest in the default
 * set (docs/app.md §Table presentation).
 */
export function cellMaxPx(key: string, shoes: readonly Shoe[], idx: TestIndex,
  scoreKeys: ReadonlySet<string>): number {
  if (scoreKeys.has(key)) return SCORE_CELL_CHARS * FIGURE_ADVANCE_PX;
  let widest = 0;
  for (const shoe of shoes) {
    let px: number;
    if (key === 'releasedAt') {
      px = textPx(displayReleaseDate(shoe.releasedAt, shoe.releaseDateSource), PHRASE_PX);
    } else if (key === 'plate') {
      px = textPx(PLATE_LABELS[shoe.plate], PHRASE_PX);
    } else {
      const cat = categoricalValue(shoe, key, idx);
      if (cat !== undefined) px = textPx(cat, PHRASE_PX);
      else {
        const v = key === 'score' ? shoe.score : numericValue(shoe, key, idx);
        px = (v === null || v === undefined ? 1 : displayNumber(v).length) * FIGURE_ADVANCE_PX;
      }
    }
    if (px > widest) widest = px;
  }
  return widest;
}

/**
 * The widest the NAME cell renders, padding excluded — the name column's own `cellMaxPx`, and a
 * function of its own rather than a branch of that one because nothing about it is shared: the cell
 * is a flex row of a chevron, a gap and a name in the bold face, with a chip after the name on the
 * shoes that carry one (`ShoeTable.svelte`, `.name-row`).
 *
 * The name is the one cell in the table that WRAPS, so its minimum is a word rather than a string —
 * `nameCellMinPx` below (docs/app.md §Table presentation).
 */
export function nameCellMaxPx(shoes: readonly Shoe[]): number {
  const widest = Math.max(0, ...shoes.map((s) =>
    textPx(s.name, NAME_PX) + (s.discontinued ? DISC_TAG_PX : 0)));
  return CHEV_PX + NAME_ROW_GAP_PX + widest;
}

/**
 * The same cell at min-content: the chevron, the gap and the widest single WORD the fleet's names
 * carry — `wordsOf`'s word, so `Speedgoat-2024` is one of them and not two. The furniture is
 * additive for the reason `headerMinPx` gives — flex items cannot break apart — and the word rather
 * than the name because this is the one cell that wraps.
 *
 * **The discontinued chip is glued to the name's LAST word, and that is markup rather than
 * choice.** `<strong>{name}</strong><DiscontinuedTag/>` carries no whitespace between the two, and
 * a chip's `margin-left` is not a break opportunity, so no engine breaks there: measured on the
 * real fleet, the widest name cell in the table is `On Cloudmonster` — one 12-character word with
 * the whole chip behind it. A chip trailing a SHORT final word costs the column nothing, since the
 * pair can wrap under a wider word ahead of it, which is why the term is per word and not per name.
 *
 * It is a floor under a floor: `columnPx('name')` takes the wider of this and `NAME_COL_PX`. While
 * the table laid itself out, a name that crossed that floor merely widened the column and only
 * `hunt/fit-boundary.mjs` would have noticed; now that the width is declared it is an overflowing
 * cell instead, and the fleet is upstream's
 * (docs/specs/2026-08-03-virtualising-the-table.md §Decisions).
 */
export function nameCellMinPx(shoes: readonly Shoe[]): number {
  const widest = Math.max(0, ...shoes.map((s) => {
    const parts = wordsOf(s.name);
    return Math.max(0, ...parts.map((w, i) =>
      textPx(w, NAME_PX) + (s.discontinued && i === parts.length - 1 ? DISC_TAG_PX : 0)));
  }));
  return CHEV_PX + NAME_ROW_GAP_PX + widest;
}

/**
 * What the model is: one memoised width per column, over the fleet that is actually loaded. Built
 * once per dataset, because the widest phrase in a column is a fact about the data and nothing a
 * runner does can change it — while the set of columns on screen changes with every tick of the
 * picker, which is why the width is per column and the sum is per call.
 *
 * Both widths answer for `name` as well as for the ticked columns, which no `columns` array ever
 * holds: the name column is the table's first, so a rule that shares a track across the whole table
 * has to be able to ask about it, and a model that answered for one of its two widths and not the
 * other would be a trap for the caller that asked the wrong one.
 */
export interface FitModel {
  /** The column's min-content width including its cell padding. */
  columnPx(key: string): number;
  /** The same column at max-content: what it would take if nothing in it had to wrap. */
  columnMaxPx(key: string): number;
}

/**
 * The score columns, from the pair registry rather than from the scoring engine: a further story
 * arrives here with no edit, and this file needs to know only that these are the columns whose
 * values come from the view rather than from the dataset (docs/app.md §The story scores).
 */
const SCORE_COLUMN_KEYS: ReadonlySet<string> = new Set(
  DERIVED_ZONE_PAIRS.flatMap((p) => [p.heel, p.forefoot]));

/**
 * One model per dataset, wherever it is asked for. The memo is what makes the model cheap — a
 * column's width is a walk of the whole fleet's strings — and two callers building their own
 * instances would each pay for it: `Page.svelte` asks which rendering fits, and `ShoeTable.svelte`
 * asks how to share its track, off the same `data` object.
 *
 * Keyed on the dataset alone, which is sound because `index` is a pure function of `data.tests`
 * (`indexTests`) and every caller derives it that way — the argument exists to avoid recomputing
 * it, never to model a different catalogue over the same shoes. A caller with an index built from
 * anything else must not use this function.
 *
 * A `WeakMap`, so a dataset that goes out of scope takes its widths with it: the suite builds a
 * fresh `ShoesFile` per case and nothing here should outlive one.
 */
const MODELS = new WeakMap<ShoesFile, FitModel>();

export function fitModel(data: ShoesFile, index?: TestIndex): FitModel {
  const cached = MODELS.get(data);
  if (cached) return cached;
  const model = buildFitModel(data, index);
  MODELS.set(data, model);
  return model;
}

function buildFitModel(data: ShoesFile, index?: TestIndex): FitModel {
  const idx = index ?? indexTests(data.tests);
  const mins = new Map<string, number>();
  const maxes = new Map<string, number>();
  const memo = (cache: Map<string, number>, key: string, compute: () => number): number => {
    const hit = cache.get(key);
    if (hit !== undefined) return hit;
    const px = compute();
    cache.set(key, px);
    return px;
  };
  return {
    columnPx(key: string): number {
      // The name column's minimum is `NAME_COL_PX` or the fleet's own longest unbreakable token,
      // whichever is wider (`nameCellMinPx`). The floor is what binds on today's fleet, by a third
      // of a pixel — `fit.test.ts` pins that headroom — and a fleet that crossed it would overflow
      // the cell, the width being declared rather than negotiated with the engine.
      // Reading the whole cell here instead would report the widest whole NAME, which is a
      // max-content and would push every mount decision hundreds of pixels out.
      if (key === 'name') {
        return memo(mins, key, () => Math.max(NAME_COL_PX, nameCellMinPx(data.shoes)) + CELL_PAD_PX);
      }
      return memo(mins, key, () => {
        const test = idx.bySlug.get(key);
        return CELL_PAD_PX + Math.max(headerMinPx(key, test),
          cellMaxPx(key, data.shoes, idx, SCORE_COLUMN_KEYS));
      });
    },
    columnMaxPx(key: string): number {
      return memo(maxes, key, () => {
        const test = idx.bySlug.get(key);
        const cells = key === 'name'
          ? nameCellMaxPx(data.shoes)
          : cellMaxPx(key, data.shoes, idx, SCORE_COLUMN_KEYS);
        return CELL_PAD_PX + Math.max(headerMaxPx(key, test), cells);
      });
    },
  };
}

/**
 * The desktop table's min-content width, panel borders included — what has to fit the content track.
 * The name column comes through the model like every other, which is what keeps the floor it is
 * built on stated once (`columnPx`, above).
 */
export function desktopMinWidth(columns: readonly string[], model: FitModel): number {
  return model.columnPx('name') + WRAPPER_BORDER_PX
    + columns.reduce((sum, col) => sum + model.columnPx(col), 0);
}

/**
 * How the desktop table shares a DECLARED track between its columns — the `<colgroup>`, one width
 * per rendered column with the name column first, summing to `trackPx` exactly.
 *
 * `trackPx` is the table's own width, `WRAPPER_BORDER_PX` excluded: `desktopMinWidth` answers what
 * the PANEL has to be given, and this answers what the table inside it does with what it got.
 *
 * **The table always fills its track**, which is a decision rather than an arithmetic necessity. A
 * model is free not to stretch and a compact table reads better on two columns — but the expanded
 * row lays out against the TABLE's width, not the window's (docs/app.md §The expanded row), so a
 * table left at its natural width lays the panel out in a single stacked column
 * (docs/specs/2026-08-03-virtualising-the-table.md §Decisions).
 *
 * **Two clauses, and the second is the one that is easy to leave out.**
 *
 * 1. While the slack is no more than the columns collectively still want, each column takes
 *    `min + slack × want / Σwant`, where `want` is its own `max − min`. `Released`, `Price`,
 *    `Plate` and `Weight` carry nowrap phrases or unbreakable mono figures and want nothing at all,
 *    so giving them width is waste — the only column that reads better wider is the one that wraps.
 * 2. Past that point every column is at its max and the excess is shared in proportion to
 *    **max-content**. Without this clause a table of figure columns — where every `want` is zero —
 *    gets `0/0` and stops short of its track by the whole excess. The alternative of giving the
 *    excess to the name column was measured and lost: every figure column is right-aligned and the
 *    last one ends at the track's edge whatever happens, so the only thing the rule can move is
 *    where the figures START, and the name column takes them 159px further right at three columns.
 *
 * A column's max is floored at its own min here, and that is not defensive tidying: the name
 * column's minimum is a DECLARED `14rem` floor rather than its content (`columnPx`), so on any
 * fleet whose names are shorter than that the max-content sits UNDER the minimum, and a share taken
 * in proportion to the smaller number would hand that column less than the engine will honour.
 * Flooring makes `want` non-negative and clause two start from a width nothing can clip out of.
 *
 * Negative slack is clamped for the same one-sided reason. This is only ever called where the table
 * has been judged to fit (`rendersPhone`), but a track under the sum of the minimums must overrun
 * the panel rather than clip a cell (spec §Failure behaviour).
 */
export function columnWidths(columns: readonly string[], trackPx: number,
  model: FitModel): number[] {
  const keys = ['name', ...columns];
  const mins = keys.map((k) => model.columnPx(k));
  const maxes = keys.map((k, i) => Math.max(mins[i]!, model.columnMaxPx(k)));
  const totalMin = mins.reduce((a, b) => a + b, 0);
  const totalMax = maxes.reduce((a, b) => a + b, 0);
  const totalWant = totalMax - totalMin;
  const slack = Math.max(0, trackPx - totalMin);
  if (totalWant > 0 && slack <= totalWant) {
    return mins.map((min, i) => min + slack * ((maxes[i]! - min) / totalWant));
  }
  const excess = slack - totalWant;
  return maxes.map((max) => max + excess * (max / totalMax));
}

/**
 * The first layout width at which the sidebar takes a column of its own beside **these** columns:
 * the floor, or the width at which the table still clears the track by the fit rule's own slack,
 * whichever is further out (docs/app.md §Filters).
 *
 * The `max` is the whole rule, and it is what makes the two decisions one. The track costs the table
 * 260px at a single pixel of window, so a permanence boundary that cannot see the column set stands
 * the sidebar up at a width where the fit rule then refuses the table — and the rendering reads
 * desktop → list → desktop as the window is dragged WIDER. Moving the constant closes that for one
 * column set and leaves it open for every wider one — a nine-column view handed 170px of width back
 * to the stacked list at exactly 1191px — because a constant cannot answer a question about a set
 * the runner picks. Consulting the model closes it for every set at once, and gives the stronger
 * property the sidebar was always supposed to have: **it never stands beside the stacked list**,
 * because it waits for the table it exists to tune.
 */
export function sidebarPermanentAt(columns: readonly string[], model: FitModel): number {
  return Math.max(SIDEBAR_PERMANENT_PX,
    desktopMinWidth(columns, model) + FIT_SLACK_PX + CONTENT_GUTTER_PX + SIDEBAR_TRACK_PX);
}

/** Whether the sidebar is a column rather than a drawer at this layout width — the predicate
 *  `Page.svelte` drives the layout, the drawer's focus trap and the `Filters` trigger from, so all
 *  of them answer one boundary (docs/app.md §Filters). */
export function sidebarPermanent(columns: readonly string[], layoutWidth: number,
  model: FitModel): boolean {
  return layoutWidth >= sidebarPermanentAt(columns, model);
}

/** What the table has to lay itself out in: the width less the page's own gutter, less the
 *  sidebar's track wherever the sidebar has one (docs/app.md §Filters). */
export function availableForTable(columns: readonly string[], layoutWidth: number,
  model: FitModel): number {
  return layoutWidth - CONTENT_GUTTER_PX
    - (sidebarPermanent(columns, layoutWidth, model) ? SIDEBAR_TRACK_PX : 0);
}

/** The question in one line: would the desktop table fit, with the slack it is held to? */
export function fitsDesktop(columns: readonly string[], availableWidth: number,
  model: FitModel): boolean {
  return desktopMinWidth(columns, model) + FIT_SLACK_PX <= availableWidth;
}

/**
 * The mount decision itself, so the floor and the fit rule have one home and `Page.svelte` reads a
 * single predicate. `layoutWidth` is the LAYOUT width — `documentElement.clientWidth`, which excludes
 * a classic scrollbar — because that is the width the table is laid out in and the fleet is always
 * long enough to draw one.
 *
 * Monotone in the width by construction, which is the property that matters most here: below
 * `sidebarPermanentAt` the available width is `layoutWidth - 16` and rises with the window, above it
 * `layoutWidth - 276`, and the boundary is *defined* as a width at which the second still clears the
 * table's minimum. So the step down at the boundary can never cross the requirement, and a rendering
 * once mounted survives every wider window
 * (docs/app.md §Two renderings, and only one of them mounted).
 */
export function rendersPhone(columns: readonly string[], layoutWidth: number,
  model: FitModel): boolean {
  if (layoutWidth < DESKTOP_FLOOR_PX) return true;
  return !fitsDesktop(columns, availableForTable(columns, layoutWidth, model), model);
}
